### ISSUE TITLE
Node.js support

### ISSUE THREAD

**Issue by jack-guy** [sopel39/audioconverter.js#2]
I'd love to see this tool modified for Node.js support and put on npm. Any plans to do so?

**Comment by sopel39** [comment]
Hi, I might do that. However, currently emscripten does not support real files in node.js with its FileAPI. Additionally, node.js is substantially slower than Firefox.

**Comment by jack-guy** [comment]
Are you sure? Node.js is based on the Chrome V8 engine, which is one of the faster JS interpreters out there. It also has a lot of i/o features.

Of course, I'm not familiar at all with emscripten, so I don't really know what I'm talking about.

**Comment by sopel39** [comment]
Firefox has special compiler for ASM code, while V8 does not, so ASM code runs significally slower on V8 (about 10x native from what I have seen).  Google, on the other hand, promotes its Portable Native Client, which is basically a C compiler to a special bytecode, which can be run with almost native speed in Chrome.

**Comment by jack-guy** [comment]
Thanks for the explanation.
