### ISSUE TITLE
Fire Fox Mobile (Android) Problem

### ISSUE THREAD

**Issue by oleksandr-lisunov-git** [sopel39/audioconverter.js#3]
Hi, when i try convert wav to mp3 my browser FIre Fox Mobile (Android) is shut down. Please help to fix this problem.

**Comment by sopel39** [comment]
Firefox on android is just a wrapper around android native webkit browser, therefore it does not support asm.js.You can have more luck with pnacl from google, which has similar purpose as asm.js, but is for chrome.
